package rlaproject;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Avi Kathuria
 */
public class admin_data extends javax.swing.JFrame {
    Connection con;
        public admin_data() {
        initComponents();
        this.setLocationRelativeTo(null);
        myconnection_class mycon1=new myconnection_class();
        if(mycon1.my_connection_status()==true)
        {
            con=mycon1.get_my_connection();
            //JOptionPane.showMessageDialog(rootPane, "connected");
        }
         else
        {
            JOptionPane.showMessageDialog(rootPane, mycon1.errmsg().toString());
         }   
          
        c1.setVisible(false);
        l1.setVisible(false);
        c2.setVisible(false);
        l2.setVisible(false);

    }
        
     public void table(String str,DefaultTableModel mymodel)
       {
           myconnection_class mycon1=new myconnection_class();
            try{      
          Statement st=con.createStatement();
          ResultSet myresult=st.executeQuery(str);
         ResultSetMetaData mycols=myresult.getMetaData();
         int col_count=mycols.getColumnCount();
         String[] colnames=new String[col_count];
         for(int c=0;c<col_count;c++)
         {
             colnames[c]=mycols.getColumnName(c+1).toString();

         }
         mymodel.setColumnIdentifiers(colnames);
        mymodel.setRowCount(0);
        while( myresult.next())
        {
         Object[] newrow=new Object[col_count];

            for(int c=0;c<col_count;c++)
         {
             newrow[c]=myresult.getObject(c+1).toString();
         }
         mymodel.addRow(newrow);
        }
      }
      catch(Exception ex)
      {
           JOptionPane.showMessageDialog(rootPane, ex.toString());
      }  
            
       }
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox();
        c2 = new javax.swing.JComboBox();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Data");
        setBackground(new java.awt.Color(0, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rlaproject/rla_images/Admin_cover.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 0, -1, -1));

        jButton5.setText("Login Details");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jButton6.setText("User Passwords");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jButton7.setText("Registration Form Details");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jButton8.setText("Licensing Form Details");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 120, -1, -1));

        jButton9.setText("Check Feedbacks");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 120, -1, -1));

        jButton10.setText("Add New User");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1037, 120, -1, -1));

        jScrollPane2.setBorder(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 268, 116));

        jScrollPane1.setBorder(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 1322, 320));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1342, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rlaproject/rla_images/admin_logo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1266, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rlaproject/rla_images/admin_logo.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setText("Sign Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1197, 120, -1, -1));

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Form 20", "Form 25", "Form 26", "Form 27", "Form 28", "Form 29", "Form 31", "Form 32", "Form 34", "Form 35", "Form 60" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Form 1", "Form 4", "Form 4(a)", "Form 8", "Form 9", "Form LLD", "Form T.R. 6" }));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, -1, -1));

        l1.setText("Choose Form");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        l2.setText("Choose Form");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 161, -1, 19));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1340, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new User_Details().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        new register().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        c1.setVisible(false);
        l1.setVisible(false);
        c2.setVisible(false);
        l2.setVisible(false);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(true);
        DefaultTableModel mymodel=(DefaultTableModel)jTable2.getModel();
      String str="select username,password from dbo.logindb";
      table(str,mymodel);
    }//GEN-LAST:event_jButton6ActionPerformed

   
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        c1.setVisible(false);
        l1.setVisible(false);
        c2.setVisible(false);
        l2.setVisible(false);
        jScrollPane2.setVisible(false);
        jScrollPane1.setVisible(true);
        DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
        String str="select Name,Designation,Comments from Feedback";
       table(str,mymodel);
    
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        c2.setVisible(false);
        l2.setVisible(false);
        c1.setVisible(true);
        l1.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        c1.setVisible(false);
        l1.setVisible(false);
        c2.setVisible(true);
        l2.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
          if(c1.getSelectedItem()=="Form 20")
        {
            jScrollPane1.setVisible(true);
            DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
             String str="select * from form20";
            table(str,mymodel);
        }
        else if(c1.getSelectedItem()=="Form 25")   
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from form25";
           table(str,mymodel);
        }
         else if(c1.getSelectedItem()=="Form 26")
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from form26";
           table(str,mymodel);
        }
        else if(c1.getSelectedItem()=="Form 27")
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from form27";
           table(str,mymodel);
        }
        else if(c1.getSelectedItem()=="Form 28")
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from form28";
           table(str,mymodel);
        }
        else if(c1.getSelectedItem()=="Form 29")
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from form29";
           table(str,mymodel);
        }
        else if(c1.getSelectedItem()=="Form 31")
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from form31";
           myconnection_class mycon=new myconnection_class();
           table(str,mymodel);
        }
        else if(c1.getSelectedItem()=="Form 32")
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from form32";
           table(str,mymodel);
        }
        else if(c1.getSelectedItem()=="Form 34")
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from Form34";
           table(str,mymodel);
        }
        else if(c1.getSelectedItem()=="Form 35")
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from form35";
           table(str,mymodel);
        }
        else if(c1.getSelectedItem()=="Form 60")
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from form60";
           table(str,mymodel);
        }
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        if(c2.getSelectedItem()=="Form 1")
        {
            jScrollPane1.setVisible(true);
            DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
             String str="select * from form1";
            table(str,mymodel);
        }
        else if(c2.getSelectedItem()=="Form 4")   
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from form4";
           table(str,mymodel);
        }
         else if(c2.getSelectedItem()=="Form 4(a)")
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from form4a";
           table(str,mymodel);
        }
        else if(c2.getSelectedItem()=="Form 8")
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from Form8";
           myconnection_class mycon=new myconnection_class(); 
           table(str,mymodel);
        }
        else if(c2.getSelectedItem()=="Form 9")
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from Form9";
           table(str,mymodel);
        }
        else if(c2.getSelectedItem()=="Form LLD")
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from formlld";
           table(str,mymodel);
        }
        else if(c2.getSelectedItem()=="Form T.R. 6")
        {
           jScrollPane1.setVisible(true);
           DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
           String str="select * from chalan";
           table(str,mymodel);
        }
    }//GEN-LAST:event_c2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_data().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    // End of variables declaration//GEN-END:variables
}
