package rlaproject;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author Avi Kathuria
 */
public class form31 extends javax.swing.JFrame {

    /** Creates new form form31 */
    Connection con;
    public form31() {
        initComponents();
        this.setLocationRelativeTo(null);
        myconnection_class mycon1=new myconnection_class();
     if(mycon1.my_connection_status()==true)
     {
         con=mycon1.get_my_connection();
        // JOptionPane.showMessageDialog(rootPane, "connected");
     }
      else
     {
         JOptionPane.showMessageDialog(rootPane, mycon1.errmsg().toString());
      }      
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        t10 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        certificate = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Form");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("FORM 31");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 0, 87, 18));

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel2.setText("Application for intimation of transfer of ownership in the name of the person succeeding to the possession of the vehicle.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, 708, 18));

        jLabel7.setText("To");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 61, 94, 18));

        jLabel8.setText("The Registering Authority");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 85, 165, 18));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 109, 178, -1));

        jLabel9.setText("1)  Vehicle Registration No. (make & model)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 149, 269, -1));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 148, 289, -1));

        jLabel12.setText("Chassis No");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 181, 135, 18));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 179, 289, -1));

        jLabel14.setText("Engine No");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 205, 135, 18));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 205, 289, -1));

        jLabel16.setText("Type of Vehicle");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 229, 135, 18));
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 231, 289, -1));

        jLabel18.setText("2)  Name of deceased registered owner");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 267, 235, 17));
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 264, 289, -1));
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 302, 236, -1));

        jLabel20.setText("3)  Name of the person succeeding to the possession of the vehicle");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 305, 401, -1));

        jLabel22.setText("Relation");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 344, 71, 18));

        t8.setText("Son/Wife/Daughter of");
        getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 343, 289, -1));

        jLabel25.setText("Full Postal Address");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 370, 165, 18));
        getContentPane().add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 369, 289, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 512, -1, -1));

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 512, -1, -1));

        jLabel27.setText("4)  Relationship with the deceased registered owner");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 403, 407, -1));

        t10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t10ActionPerformed(evt);
            }
        });
        getContentPane().add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 400, 289, -1));

        jLabel30.setText("Certificate of registration is enclosed herewith. Kindly transfer the ownership of the vehicle in my name.");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 451, -1, -1));

        certificate.setText("File Upload");
        certificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificateActionPerformed(evt);
            }
        });
        getContentPane().add(certificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 471, -1, -1));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 512, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rlaproject/rla_images/Icon.jpg"))); // NOI18N
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try
        {
            int d1_len=t1.getText().length();
            int d2_len=t2.getText().length();
            int d3_len=t3.getText().length();
            int d4_len=t4.getText().length();
            int d5_len=t5.getText().length();
            int d6_len=t6.getText().length();
            int d7_len=t7.getText().length();
            int d8_len=t8.getText().length();
            int d9_len=t9.getText().length();
            int d10_len=t10.getText().length();
            if(d1_len==0 || d2_len==0 || d3_len==0 || d4_len==0 || d5_len==0 || d6_len==0 || d7_len==0 || d8_len==0 || d9_len==0 || d10_len==0)
              {
                JOptionPane.showMessageDialog(rootPane, "Please Fill Required Fields to Submit the Form");
                if(d1_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Authority Name ");
                } 
                else if(d2_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Vehicle Reg. No.");
                } 
                else  if(d3_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Chassis No.");
                } 
                else if(d4_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Engine No.");
                }  
                else if(d5_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Type of Vehicle");
                }  
                else if(d6_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Name of Deceased Owner");
                }  
                else if(d7_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Name of Succeeding Owner");
                }
                else if(d8_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Relation ");
                } 
                else if(d9_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Postal Address");
                } 
               else  if(d10_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Relationship with Deceased Owner");
                }    
          }
           else
           {        
            int res=JOptionPane.showConfirmDialog(null,"Want to Submit Form","Info",JOptionPane.OK_OPTION,JOptionPane.INFORMATION_MESSAGE);
           if(res==JOptionPane.OK_OPTION)
           {
               PreparedStatement pstmt=con.prepareStatement("insert into form31 values(?,?,?,?,?,?,?,?,?,?,?,?)");
               pstmt.setString(1,(t1.getText()));
               pstmt.setString(2,(t2.getText()));
               pstmt.setString(3,(t3.getText()));
               pstmt.setString(4,(t4.getText()));
               pstmt.setString(5,(t5.getText()));
               pstmt.setString(6,(t6.getText()));
               pstmt.setString(7,(t7.getText()));
               pstmt.setString(8,(t8.getText()));
               pstmt.setString(9,(t9.getText()));
               pstmt.setString(10,(t10.getText()));
               pstmt.setString(11,(f2.getPath()));
                java.util.Date d1=new java.util.Date();
                   String newdate=new SimpleDateFormat("dd/MM/yyyy").format(d1);
                   pstmt.setString(12,newdate);  
               pstmt.executeUpdate(); 
               FileUtils.copyFileToDirectory(f1, f2);
               new main().setVisible(true);
               dispose();
           }
        }
    }                                     
           catch(Exception obj)
        {
            System.out.println(obj.toString());
            JOptionPane.showMessageDialog(rootPane, "Please Upload Required File in the Form");
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void t10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t10ActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
         t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        t7.setText("");
        t8.setText("");
        t9.setText("");
        t10.setText("");

    }//GEN-LAST:event_ClearActionPerformed
    File f1,f2;
    private void certificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificateActionPerformed
        JFileChooser JFC = new JFileChooser();

        if( JFC.showOpenDialog(null)==0)
        {

            f1=new File(JFC.getSelectedFile().toString());
            f2=new File("C:\\rlaproject\\Uploaded_Files");
        }
    }//GEN-LAST:event_certificateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new main().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form31().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton certificate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables

}
