package rlaproject;

import java.io.File;
import java.sql.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.io.FileUtils;
import java.text.SimpleDateFormat;
/**
 *
 * @author Avi Kathuria
 */
public class formlld extends javax.swing.JFrame {

    /** Creates new form form1 */
    public formlld() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
           myconnection_class mycon1=new myconnection_class();
        if(mycon1.my_connection_status()==true)
        {
            con=mycon1.get_my_connection();
           // JOptionPane.showMessageDialog(rootPane, "connected");
        }
         else
        {
            JOptionPane.showMessageDialog(rootPane, mycon1.errmsg().toString());
         }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel61 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        t10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        h1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();

        jLabel61.setText("jLabel61");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Licensing Form");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("FORM L.L.D.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 111, 22));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 113, 260, 22));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("APPLICATION FOR DUPLICATE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 228, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("To");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("The Licensing Authority");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 115, 144, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("I");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 15, -1));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 138, 164, -1));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 344, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("of");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("(Permanent Address)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 370, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Father's Name");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText(" has been lost or destroyed in the following circumstances:-");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 374, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        t4.setText("Mr.");
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 254, -1));
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 168, -1));

        jLabel20.setText("Returned to the Licensing Authority ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 20));
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 279, -1));

        jLabel21.setText("Number");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 20));
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 279, -1));

        jLabel22.setText("Date of issue");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 20));
        getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 279, -1));

        jLabel23.setText("Date of Expiry");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 20));
        getContentPane().add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 279, -1));

        jLabel24.setText("Class of vehicle");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 20));
        getContentPane().add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 279, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));

        h1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        h1.setText("I hereby apply for a duplicate license and tender ten rupees n the form of Judicial stamps.");
        getContentPane().add(h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        jButton3.setText("Upload Image");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 123, 133));

        jLabel3.setText("[Rule 29(1) of Punjab Motor Vehicle Act. 1943]");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel4.setText("Intimation of Loss of Destruction of License and");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 270, -1));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("day of");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 50, 20));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rlaproject/rla_images/Icon.jpg"))); // NOI18N
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
            Connection con;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            int d1_len=t1.getText().length();
            int d2_len=t2.getText().length();
            int d3_len=t3.getText().length();
            int d4_len=t4.getText().length();
            int d5_len=t5.getText().length();
            int d6_len=t6.getText().length();
            int d7_len=t7.getText().length();
            int d8_len=t8.getText().length();
            int d9_len=t9.getText().length();
            int d10_len=t10.getText().length();
            if(d1_len==0 || d2_len==0 || d3_len==0 || d4_len==0 || d5_len==0 || d6_len==0 || d7_len==0 || d8_len==0 || d9_len==0 || d10_len==0 )
             {
                JOptionPane.showMessageDialog(rootPane, "Please Fill Required Fields to Submit the Form");
                if(d1_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Authority Name ");
                } 
                else if(d2_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Name");
                } 
                else  if(d3_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Address");
                } 
                else if(d4_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Father's Name");
                }  
                else if(d5_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Date of Lost");
                }  
                else if(d6_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Details of Returned to Authority");
                }  
                else if(d7_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Number");
                }
                else if(d8_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Date of Issue");
                } 
                else if(d9_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Date of Expiry");
                } 
               else  if(d10_len==0)
                {
                JOptionPane.showMessageDialog(rootPane, "Please insert Class of Vehicle");
                }    
              }
            else
            { 
              int res=JOptionPane.showConfirmDialog(null,"Want to Submit Form","Info",JOptionPane.OK_OPTION,JOptionPane.INFORMATION_MESSAGE);
             if(res==JOptionPane.OK_OPTION)
                {
                    PreparedStatement pstmt=con.prepareStatement("insert into formlld values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
             
             pstmt.setString(1,(t1.getText()));
             pstmt.setString(2,(t2.getText()));
             pstmt.setString(3,(t3.getText()));
             pstmt.setString(4,(t4.getText()));
             pstmt.setString(5,(t5.getText())); 
             
            String judicial_stamp="No";
           if(h1.isSelected())
             {
                judicial_stamp="Yes";
             }
             pstmt.setString(6,judicial_stamp);
        
              pstmt.setString(7,(t6.getText()));
              pstmt.setString(8,(t7.getText()));
              pstmt.setString(9,(t8.getText()));
              pstmt.setString(10,(t9.getText()));
              pstmt.setString(11,(t10.getText()));
              
            java.util.Date d1=new java.util.Date();
            String newdate=new SimpleDateFormat("dd/MM/yyyy").format(d1);
            pstmt.setString(12,newdate); 
            
              pstmt.setString(13,(f2.getPath()));
             
              FileUtils.copyFileToDirectory(f1, f2);
                    pstmt.executeUpdate();
                    new main().setVisible(true);
                    dispose();
          }  
      }
    }//GEN-LAST:event_jButton1ActionPerformed
        catch(Exception obj)
            {
            System.out.println(obj.toString());
            JOptionPane.showMessageDialog(rootPane, "Please Upload Required Image in the Form");
           }
 
    }
 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       t1.setText("");
       t2.setText("");
       t3.setText("");
       t4.setText("");
       t5.setText("");
       t6.setText("");
       t7.setText("");
       t8.setText("");
       t9.setText("");
       t10.setText("");   
    }//GEN-LAST:event_jButton2ActionPerformed
File f1,f2;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser JFC = new JFileChooser();
        
        if( JFC.showOpenDialog(null)==0)
        {
         
             f1=new File(JFC.getSelectedFile().toString());
           f2=new File("C:\\rlaproject\\Uploaded_Files");
        }        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new main().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
 
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formlld().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox h1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables

}
